# Generated by Django 5.2.14 on 2026-06-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_dual_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='tl_approved_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='tl_approved_by',
        ),
    ]
